### ISSUE TITLE
Not working with Tailscale

### ISSUE THREAD

**Issue by InfiniteAvenger** [streamyfin/streamyfin#11]
Hi I’m on iOS beta 18. I use the Tailscale vpn to remote in to my server. It has worked with every other Jellyfin client and any other services I use on my server. However with this app, I’m getting an error saying to make sure I’m on the correct network. Does this not work with Tailscale?

**Comment by fredrikburmester** [comment]
Hi it should work with Tailscale without issue. I'm gonna do some testing and get back to you.

**Comment by KomGiann** [comment]
Same error

**Comment by CalebWest2** [comment]
Now that I am home I've tried with my IP address and it works, but it still does not work with Tailscale. Other than that everything looks great! I would love a third tab on the bottom that shows the different media libraries grouped, but I know this is still a very very early beta

**Comment by YannikBe** [comment]
Same problem here. 
Awesome project though!

**Comment by fredrikburmester** [comment]
This should be solved in the latest (0.3.1) release!

**Comment by ebits21** [comment]
If I use the Tailscale ip address of the server like http://100.100.100.100:8096/ it fails with an error.

But if I use http://servername:8096/ where servername is the Tailscale name for the server it works fine.

On iOS 17

**Comment by ebits21** [comment]
Just confirming 0.4.1 fixes the issue for me.

**Comment by YannikBe** [comment]
> If I use the Tailscale ip address of the server like http://100.100.100.100:8096/ it fails with an error.
> 
> But if I use http://servername:8096/ where servername is the Tailscale name for the server it works fine.

On iOS 17 on an iPhone 15 Pro connecting through Tailscale still doesn't work. Tested with IP, device name and MagicDNS entry. The same is working just fine when using the official Jellyfin app. 

All login methods are behaving the same for me: the login screen makes way for the app's main menu which loads for a few seconds before showing the error message you can see in the screenshot.
Logging out and in again or reinstalling the entire app did not help.

![image](https://github.com/user-attachments/assets/789a5929-562b-41c1-8e54-958e9d081c1e)

**Comment by fredrikburmester** [comment]
@YannikBe can you try the demo server? 

Server: `https://jellyfin-test.fdrive.se`
User: `apple`
Pass: `123456`

And see if it has the same behaviour for you?

**Comment by YannikBe** [comment]
The test server is working flawlessly!

**Comment by fredrikburmester** [comment]
Hmm ok that probably means there is something with your server or the content in it that is causing an error within my app. If you want you can share your server with me _privately_ so I can test?

**Comment by YannikBe** [comment]
@fredrikburmester Thanks a lot for the offer! Unfortunately I have to say that I wouldn't be comfortable sharing my instances credentials.
I will try to look into it on the weekend, though, and report back with any findings :)

**Comment by MulverineX** [comment]
I'm using headscale and its working perfectly, I hope OP can figure out their issue though 😄
