### ISSUE TITLE
Feature Request: Comprehensive Feature Enhancements & UI Polish

### ISSUE THREAD

**Issue by skyzea1** [streamyfin/streamyfin#757]
### Is your feature request related to a problem? Please describe.

This issue combines several feature suggestions to enhance Streamyfin's capabilities and user experience. 

### Describe the solution you'd like

We propose the following features and improvements:

**Core Feature Enhancements:**

1.  **Expanded Subtitle Support (including OpenSubtitles.org):** Integrate with OpenSubtitles.org and potentially other subtitle services to allow users to find and download a wider range of subtitles directly within the app.
2.  **Audio Track Selection:** Allow users to select different audio tracks if the media file contains multiple (e.g., different languages, commentary tracks).
3.  **Playback Speed Control:** Implement controls for speeding up or slowing down video playback.
4.  **Improved Offline Mode:**
    *   More robust download management (e.g., queuing, background downloads).
    *   Ability to select download quality/resolution.
5.  **User Profiles:** Allow for distinct user profiles within the app to remember individual playback progress, preferences, etc.
6.  **Customizable UI/Themes:** Provide options for users to personalize the app's appearance.
7.  **Direct Trakt.tv Integration:** Enable scrobbling of watch history to Trakt.tv.
8.  **"Picture-in-Picture" (PiP) Mode:** For mobile devices, allow video to continue playing in a small window while the user interacts with other apps.
9.  **Advanced Library Filtering and Sorting:** Add more granular options for filtering (e.g., by genre, year, resolution, audio/subtitle language) and sorting media.
10. **Parental Controls:** Implement features to restrict access to content based on ratings or tags.
11. **Enhanced Video Player UI:** Redesign the video player interface for a more modern and user-friendly experience, potentially taking inspiration from established players like MX Player for improved aesthetics and usability.

**Potential Future Considerations (Long-term):**

*   **Live TV / DVR Support:** Integrate Live TV/DVR capabilities if the connected Jellyfin server supports them.

**Improvements to Existing Features:**

*   **Performance Optimization:** Continue to focus on app startup time, UI responsiveness, and streaming performance.
*   **Enhanced Chromecast Stability and Features:** Improve reliability and add features like subtitle support during casting.
*   **Accessibility Improvements:** Ensure the app is fully accessible (screen readers, keyboard navigation, contrast).
*   **More Granular Transcoding Settings (Client-Side):** Offer more control over client-side transcoding options.
*   **Clearer Error Messaging:** Provide more informative and user-friendly error messages.

### Describe alternatives you've considered

Individual feature requests could be made, but a combined issue provides a broader overview of potential enhancements.

### Additional context

These suggestions aim to make Streamyfin a more comprehensive and user-friendly Jellyfin client.

**Comment by Simon-Eklundh** [comment]
Hi there! We tend to ask that feature requests are kept to one per feature. In addition:

1. Nice idea.  

2.we already have audio track selection, both while playing and before playing
3. We've discussed this but none of us has been interested in it
4.we have queueing, just start a download then another. Quality and resolution is technically also possible (although it's bitrate based)
5. This is solved by having different jellyfin accounts
6. Unlikely to happen
7.this is solved in jellyfin (assuming you have the trakt plugin and are logged in)
8. Pip works on android, but won't be on iOS until VLC 4 is stable (or we swap players or something)
9.we already have that although it can be improved 
10. This is a thing in jellyfin, better to deal with it there
11. We've already done one redesign, if you have a specific example of what you'd like, feel free to make a proposal


We have (most of the time) live tv playback support 

We're working on improvements overall, although I don't think the granular quality setting is likely to happen unless we rewrite a bit.


Cheers!

**Comment by MrMightyNighty** [comment]
@Simon-Eklundh About iOS, pip and VLC 4: It seems like VLC 4 has been in development for quite some time (announced in 2019) and still doesn’t have a release date. I know Streamyfin already tried to implement VLC 4 but had to roll it back due to issues.
I also completely understand that switching the player isn’t a simple task.

Would it be easier to implement VLC 4 alongside VLC 3 as an experimental feature, with a toggle so users can opt in?

**Comment by Simon-Eklundh** [comment]
Iirc: we tried, but they require two different dependency versions so it didn't work

**Comment by frederiknolte** [comment]
My suggestions for modernising the Video Player controls are as follows:

1. When sliding through any of the following: video progress bar, screen brightness bar, volume bar, the current level is set to where my finger starts sliding. It would be much more convenient if the change was relative, similar to how other video players handle it. For example, assume there is a bar that is currently at 50% and I touch the bar around the 75% mark and slide my finger down the bar by about 10%. In the current behaviour, the bar immediately jumps from 50% to 75% when my finger touches it, and my sliding reduces it by 10% to 65%. Improved behaviour would be that the bar remains at 50% upon touching it around 75%, and sliding my finger down by 10% sets the bar to 40%. This is the behaviour I get from essentially any other app on iOS as well as from iOS itself.
2. Touching and holding the screen anywhere (except video control buttons) increases playback speed by 2x as long as one holds the screen. This behaviour is similar to YouTube and several other video apps and vey convenient.
3. Double tapping on the right/left side of the video playback screen should fast-forward/backward by the amount set in the settings (i.e. 15 sec, 25 sec, or whatever you set). This is also present in YouTube and several other video streaming apps.

**Comment by Simon-Eklundh** [comment]
My 2 cents: 

1. That makes sense, but if you have a bar you're literally grabbing I think it'd be weird
2. I personally really dislike that behaviour, but an option in the settings for enabling it maybe 
3.agreed

**Comment by frederiknolte** [comment]
Oh what I forgot to add to 1. is that with volume and brightness you can slide down anywhere on the right/ left side of the screen, respectively. This would also work if the control buttons are currently hidden due to the video playing. This would make changing brightness and volume a lot more immediate without first having to touch the screen for the controls to show up and then having to hit the bar exactly where I want the value to be. 
But even if you drag the bar directly, the relative behaviour is the one implemented by iOS itself. You see that for example by playing music on some app (e.g. spotify), then using the physical volume buttons to change the volume and dragging on the appearing volume control bar.

Essentially, all the features I’m asking for make the video player more similar to Infuse (another app).
